[project]
name = "translate-ppt-deepl"
version = "0.1.0"
dependencies = [
  "streamlit",
  "python-pptx",
  "requests",
  "nbformat",
  "python-dotenv",
]

[tool.hatch.envs.default]
dependencies = [
  "uv",
]